					-- MySQL Script generated by MySQL Workbench
-- Sun May 28 10:22:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PARK
-- -----------------------------------------------------
-- A DATA BASE FOR A PARK

-- -----------------------------------------------------
-- Schema PARK
--
-- A DATA BASE FOR A PARK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PARK` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `PARK` ;

-- -----------------------------------------------------
-- Table `PARK`.`visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`visitor_card` (
  `idvisitor_card` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `afm_number` VARCHAR(9) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`idvisitor_card`, `euro_charge`),
  UNIQUE INDEX `afm_number_UNIQUE` (`afm_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`canteen_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`canteen_products` (
  `idcanteen_products` INT NOT NULL AUTO_INCREMENT,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  `name_of_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcanteen_products`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`visitor_card_has_canteen_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`visitor_card_has_canteen_products` (
  `visitor_card_idvisitor_card` INT NOT NULL,
  `canteen_products_idcanteen_products` INT NOT NULL,
  PRIMARY KEY (`visitor_card_idvisitor_card`, `canteen_products_idcanteen_products`),
  INDEX `fk_visitor_card_has_canteen_products_canteen_products1_idx` (`canteen_products_idcanteen_products` ASC) VISIBLE,
  INDEX `fk_visitor_card_has_canteen_products_visitor_card_idx` (`visitor_card_idvisitor_card` ASC) VISIBLE,
  CONSTRAINT `fk_visitor_card_has_canteen_products_visitor_card`
    FOREIGN KEY (`visitor_card_idvisitor_card`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visitor_card_has_canteen_products_canteen_products1`
    FOREIGN KEY (`canteen_products_idcanteen_products`)
    REFERENCES `PARK`.`canteen_products` (`idcanteen_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`game_tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`game_tickets` (
  `idgame_tickets` INT NOT NULL AUTO_INCREMENT,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  `name_of_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgame_tickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`canteen_products_has_visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`canteen_products_has_visitor_card` (
  `charge_id` INT NOT NULL AUTO_INCREMENT,
  `canteen_products_idcanteen_products` INT NOT NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`charge_id`),
  INDEX `fk_canteen_products_has_visitor_card_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  INDEX `fk_canteen_products_has_visitor_card_canteen_products1_idx` (`canteen_products_idcanteen_products` ASC) VISIBLE,
  CONSTRAINT `fk_canteen_products_has_visitor_card_canteen_products1`
    FOREIGN KEY (`canteen_products_idcanteen_products`)
    REFERENCES `PARK`.`canteen_products` (`idcanteen_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canteen_products_has_visitor_card_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`game_tickets_has_visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`game_tickets_has_visitor_card` (
  `charge_id` INT NOT NULL AUTO_INCREMENT,
  `game_tickets_idgame_tickets` INT NOT NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`charge_id`),
  INDEX `fk_game_tickets_has_visitor_card_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  INDEX `fk_game_tickets_has_visitor_card_game_tickets1_idx` (`game_tickets_idgame_tickets` ASC) VISIBLE,
  CONSTRAINT `fk_game_tickets_has_visitor_card_game_tickets1`
    FOREIGN KEY (`game_tickets_idgame_tickets`)
    REFERENCES `PARK`.`game_tickets` (`idgame_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_tickets_has_visitor_card_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`cinema_tickets_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`cinema_tickets_copy1` (
  `idcinema_tickets` INT NOT NULL AUTO_INCREMENT,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  `name_of_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcinema_tickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`cinema_program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`cinema_program` (
  `idcinema_program` INT NOT NULL,
  `movies` VARCHAR(45) NOT NULL,
  `movies_time` DATETIME NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`idcinema_program`, `visitor_card_idvisitor_card`, `visitor_card_euro_charge`),
  INDEX `fk_cinema_program_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  CONSTRAINT `fk_cinema_program_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`comercial_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`comercial_center` (
  `idcomercial_center` INT NOT NULL AUTO_INCREMENT,
  `name_of_product` VARCHAR(45) NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  `name_of_shop` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcomercial_center`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`bicycle_tickeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`bicycle_tickeds` (
  `idbicycle_tickets` INT NOT NULL AUTO_INCREMENT,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  `name_of_product` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbicycle_tickets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`bicycle_tickeds_has_visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`bicycle_tickeds_has_visitor_card` (
  `charge_id` INT NOT NULL AUTO_INCREMENT,
  `bicycle_tickeds_idbicycle_tickets` INT NOT NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`charge_id`),
  INDEX `fk_bicycle_tickeds_has_visitor_card_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  INDEX `fk_bicycle_tickeds_has_visitor_card_bicycle_tickeds1_idx` (`bicycle_tickeds_idbicycle_tickets` ASC) VISIBLE,
  CONSTRAINT `fk_bicycle_tickeds_has_visitor_card_bicycle_tickeds1`
    FOREIGN KEY (`bicycle_tickeds_idbicycle_tickets`)
    REFERENCES `PARK`.`bicycle_tickeds` (`idbicycle_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bicycle_tickeds_has_visitor_card_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`comercial_center_has_visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`comercial_center_has_visitor_card` (
  `charge_id` INT NOT NULL AUTO_INCREMENT,
  `comercial_center_idcomercial_center` INT NOT NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`charge_id`),
  INDEX `fk_comercial_center_has_visitor_card_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  INDEX `fk_comercial_center_has_visitor_card_comercial_center1_idx` (`comercial_center_idcomercial_center` ASC) VISIBLE,
  CONSTRAINT `fk_comercial_center_has_visitor_card_comercial_center1`
    FOREIGN KEY (`comercial_center_idcomercial_center`)
    REFERENCES `PARK`.`comercial_center` (`idcomercial_center`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comercial_center_has_visitor_card_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PARK`.`cinema_tickets_copy1_has_visitor_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PARK`.`cinema_tickets_copy1_has_visitor_card` (
  `charge_id` INT NOT NULL AUTO_INCREMENT,
  `cinema_tickets_copy1_idcinema_tickets` INT NOT NULL,
  `visitor_card_idvisitor_card` INT NOT NULL,
  `visitor_card_euro_charge` FLOAT NOT NULL,
  PRIMARY KEY (`charge_id`),
  INDEX `fk_cinema_tickets_copy1_has_visitor_card_visitor_card1_idx` (`visitor_card_idvisitor_card` ASC, `visitor_card_euro_charge` ASC) VISIBLE,
  INDEX `fk_cinema_tickets_copy1_has_visitor_card_cinema_tickets_cop_idx` (`cinema_tickets_copy1_idcinema_tickets` ASC) VISIBLE,
  CONSTRAINT `fk_cinema_tickets_copy1_has_visitor_card_cinema_tickets_copy11`
    FOREIGN KEY (`cinema_tickets_copy1_idcinema_tickets`)
    REFERENCES `PARK`.`cinema_tickets_copy1` (`idcinema_tickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cinema_tickets_copy1_has_visitor_card_visitor_card1`
    FOREIGN KEY (`visitor_card_idvisitor_card` , `visitor_card_euro_charge`)
    REFERENCES `PARK`.`visitor_card` (`idvisitor_card` , `euro_charge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
